/**
 * Pure helper functions for line directive navigation.
 * No VS Code dependencies — designed for testability and reusability.
 */

// ── Detection ─────────────────────────────────────────────────────────────────

/** Returns true if the file header looks like a Bison or Flex generated C file. */
export function isGeneratedFile(text: string): boolean {
  const header = text.slice(0, 600);
  return (
    header.includes('/* A Bison parser, made by GNU Bison') ||
    header.includes('/* Generated by GNU Bison') ||
    header.includes('/* Generated by flex') ||
    header.includes('/* A lexical scanner generated by flex')
  );
}

// ── Line directive helpers ────────────────────────────────────────────────────

export interface LineDirective {
  sourceLine: number;    // 1-based line number in the source file
  sourceFile: string;
  directiveLine: number; // 0-based line index in the generated file where directive was found
}

/**
 * Scan backwards from cursorLine to find the nearest #line N "file" or #line N file directive.
 * Returns the directive data including the line index where it was found.
 */
export function findNearestLineDirective(lines: string[], cursorLine: number): LineDirective | null {
  for (let i = cursorLine; i >= 0; i--) {
    const m = lines[i].match(/^#line\s+(\d+)\s+"?([^"\s]+)"?/);
    if (m) {
      return {
        sourceLine: parseInt(m[1], 10),
        sourceFile: m[2],
        directiveLine: i,
      };
    }
  }
  return null;
}
