/**
 * Tests for lineDirectiveUtils pure helpers.
 * Run: TS_NODE_PROJECT=tsconfig.base.json npx ts-node tests/test-line-directive.ts
 */
import { isGeneratedFile, findNearestLineDirective } from '../client/src/lineDirectiveUtils';

let passed = 0, failed = 0;
function assert(cond: boolean, msg: string, extra?: unknown) {
  if (cond) { console.log(`  [PASS] ${msg}`); passed++; }
  else { console.error(`  [FAIL] ${msg}${extra !== undefined ? `  →  ${JSON.stringify(extra)}` : ''}`); failed++; }
}

// ── isGeneratedFile ────────────────────────────────────────────────────────────
console.log('\nisGeneratedFile');

assert(
  isGeneratedFile('/* A Bison parser, made by GNU Bison 3.8.2.  */\n...rest...'),
  'detects Bison generated file (made by)'
);
assert(
  isGeneratedFile('/* Generated by GNU Bison 3.8 */\n...rest...'),
  'detects Bison generated file (generated by)'
);
assert(
  isGeneratedFile('/* Generated by flex 2.6.4 */\n...rest...'),
  'detects Flex generated file (generated by flex)'
);
assert(
  isGeneratedFile('/* A lexical scanner generated by flex */\n'),
  'detects Flex generated file (lexical scanner)'
);
assert(
  !isGeneratedFile('// My hand-written parser\n'),
  'rejects non-generated file'
);
assert(
  !isGeneratedFile(''),
  'rejects empty file'
);

// ── findNearestLineDirective ───────────────────────────────────────────────────
console.log('\nfindNearestLineDirective — quoted filenames');

{
  // Cursor ON the directive line → offset = 0
  const lines = ['#line 28 "parser.y"', 'some_func();'];
  const d = findNearestLineDirective(lines, 0);
  assert(d !== null, 'quoted: finds directive on cursor line');
  if (d) {
    assert(d.sourceLine === 28, 'quoted: sourceLine = 28', d.sourceLine);
    assert(d.sourceFile === 'parser.y', 'quoted: sourceFile = parser.y', d.sourceFile);
    assert(d.directiveLine === 0, 'quoted: directiveLine = 0', d.directiveLine);
  }
}

{
  // Cursor 4 lines below the directive → offset = 4
  // The caller should compute: targetLine = sourceLine - 1 + (cursorLine - directiveLine) = 27 + 4 = 31
  const lines = [
    '#line 28 "parser.y"',
    '#include "config.h"',
    '#include <stdlib.h>',
    '#include <string.h>',
    'void some_func(int mode) {',
  ];
  const d = findNearestLineDirective(lines, 4);
  assert(d !== null, 'quoted: finds directive 4 lines above cursor');
  if (d) {
    assert(d.sourceLine === 28, 'quoted: sourceLine = 28', d.sourceLine);
    assert(d.sourceFile === 'parser.y', 'quoted: sourceFile (cursor 4 lines below)', d.sourceFile);
    assert(d.directiveLine === 0, 'quoted: directiveLine = 0', d.directiveLine);
  }
}

console.log('\nfindNearestLineDirective — unquoted filenames');

{
  // GitMensch case: no quotes
  const lines = ['#line 28 parser.y', 'some_func();'];
  const d = findNearestLineDirective(lines, 1);
  assert(d !== null, 'unquoted: finds directive');
  if (d) {
    assert(d.sourceLine === 28, 'unquoted: sourceLine = 28', d.sourceLine);
    assert(d.sourceFile === 'parser.y', 'unquoted: sourceFile = parser.y', d.sourceFile);
    assert(d.directiveLine === 0, 'unquoted: directiveLine = 0', d.directiveLine);
  }
}

{
  // Unquoted relative path
  const lines = ['#line 5 src/parser.y', 'x = 1;'];
  const d = findNearestLineDirective(lines, 1);
  assert(d !== null, 'unquoted path: finds directive');
  if (d) {
    assert(d.sourceFile === 'src/parser.y', 'unquoted path: sourceFile', d.sourceFile);
  }
}

console.log('\nfindNearestLineDirective — edge cases');

{
  // No directive anywhere → null
  const lines = ['int x = 0;', 'return x;'];
  const d = findNearestLineDirective(lines, 1);
  assert(d === null, 'returns null when no directive exists');
}

{
  // Multiple directives — picks the nearest one above cursor
  const lines = [
    '#line 10 "a.y"',
    'foo();',
    '#line 20 "b.y"',
    'bar();',
  ];
  const d = findNearestLineDirective(lines, 3);
  assert(d !== null, 'picks nearest directive above cursor');
  if (d) {
    assert(d.sourceLine === 20, 'picks nearest directive above cursor (line)', d.sourceLine);
    assert(d.sourceFile === 'b.y', 'picks nearest directive above cursor (file)', d.sourceFile);
    assert(d.directiveLine === 2, 'directiveLine of nearest directive', d.directiveLine);
  }
}

{
  // Cursor on line 0 with no directive → null
  const lines = ['int x = 0;'];
  const d = findNearestLineDirective(lines, 0);
  assert(d === null, 'no directive on line 0 → null');
}

console.log(`\nResults: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
